---
apiVersion: v1
kind: Service
metadata:
  name: {{ app_name }}-svc
  namespace: {{ namespace }}
spec:
  ports:
  - name: metrics-endpoint
    port: {{ metrics_port }}
    protocol: TCP
    targetPort: {{ metrics_port }}
  selector:
    # This selector ensures this Service identifies
    # the metacontroller workload Pod correctly as ti will have
    # the same tag. Please NOTE this is pointing at the workload
    # and not the charm. The label is assigned to the Pod via the
    # StatefulSet located in the same directory as this file.
    app.kubernetes.io/name: {{ namespace }}-{{ app_name }}-charm

