# reusable workflow triggered by other actions
name: CI

on:
  workflow_call:
    secrets:
      CHARMCRAFT_CREDENTIALS:
        required: true

jobs:
  lib-check:
    name: Check libraries
    uses: canonical/charmed-kubeflow-workflows/.github/workflows/_quality-checks.yaml@main
    secrets: inherit
    with:
        charm-path: "."

  lint:
    name: Lint
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: pip install tox
    - run: tox -vve lint
  
  terraform-checks:
    name: Terraform
    uses: canonical/charmed-kubeflow-workflows/.github/workflows/terraform-checks.yaml@main
    with:
      charm-path: .
      channel: 3.0/stable

  unit:
    name: Unit Tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install tox
      - run: tox -vve unit

  integration:
    name: Integration Tests
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Setup operator environment
      uses: charmed-kubernetes/actions-operator@main
      with:
        provider: microk8s
        channel: 1.25-strict/stable
        microk8s-addons: "dns storage rbac metallb:10.64.140.43-10.64.140.49"
        charmcaft-channel: latest/candidate
        juju-channel: 3.5/stable

    - name: Test
      run: sg snap_microk8s -c "tox -vve integration -- --model testing"

      # On failure, capture debugging resources
    - name: Get all
      run: kubectl get all -A
      if: failure()

    - name: Describe deployments
      run: kubectl describe deployments -A
      if: failure()

    - name: Describe replicasets
      run: kubectl describe replicasets -A
      if: failure()

    - name: Get juju status
      run: juju status
      if: failure()

    - name: Get application logs
      run: kubectl logs -n testing --tail 1000 -lapp.kubernetes.io/name=metacontroller-operator
      if: failure()

    - name: Get application operator logs
      run: kubectl logs -n testing --tail 1000 -loperator.juju.is/name=metacontroller-operator
      if: failure()
